apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: workshop
type: Opaque
data:
   SPRING_DATASOURCE_USERNAME: cHJpYWNjaW5ub3ZhdGlvbg==    # priaccinnovation
   SPRING_DATASOURCE_PASSWORD: cHJpYWNjaW5ub3ZhdGlvbg==
